import { useState } from 'react';
import { FileText, Flag, Link as LinkIcon, List, Send } from 'lucide-react';
import { demoAnalysis as data } from '../../mocks/analysis';
import { CategorySelector } from '../../shared/ui/CategorySelector';
import { Dialog } from '../../shared/ui/Dialog';
import s from './Analysis.module.css';

export function AnalysisPage() {
  const [source, setSource] = useState<typeof data.sources[number] | null>(null);
  const [followUp, setFollowUp] = useState('');
  const [notice, setNotice] = useState('');
  return <div className={s.page}><div className={s.toolbar}><div><CategorySelector /></div><small>Basado en el PDF aportado · Corte: 11/09/2026</small></div><section className={s.message} aria-label="Consulta de demostración"><span className="avatar">AJ</span><div><strong>Ale Jiménez</strong><time>10:24</time><p>{data.query}</p></div></section><div className={s.report}><article className={s.article}><div className={s.author}><img src="/assets/brand.svg" alt="" /><strong>Contrasta</strong><time>10:24</time></div><h1>{data.title}</h1><section className={s.textSection}><FileText /><div><h2>Contexto</h2><p>{data.context}</p></div></section><section className={s.textSection}><List /><div><h2>Síntesis</h2><p>{data.summary}</p></div></section><section className={s.verdict}><span className={s.flag}><Flag /></span><div><h2>Valoración final</h2><h3>{data.verdict}</h3><p>Respaldo documental de la acusación general: insuficiente.</p><small>No descarta irregularidades en casos concretos.</small></div></section></article>
      <aside className={s.positions}><h2>Posiciones en las publicaciones</h2><span className={s.warning}>Datos ilustrativos · no calculados del PDF</span><strong className={s.percentage}>80 %</strong><p><strong>8 de 10</strong> publicaciones cuestionan el respaldo de la acusación.</p><div className={s.bar} role="img" aria-label="Cuestiona 80 %, respalda 10 %, mixta 0 %, sin posición 10 %"><span>80%</span><span>10%</span><span>10%</span></div><ul className={s.legend}><li>Cuestiona: 8</li><li>Respalda: 1</li><li>Mixta: 0</li><li>Sin posición: 1</li></ul><div className={s.scope}><p>Ejemplo de muestra; no representa opinión pública ni probabilidad de falsedad.</p><p><strong>Importante: este porcentaje es una cifra ficticia de demostración y no se ha calculado a partir del PDF.</strong></p></div></aside>
      <section className={s.sources}><h2><LinkIcon />Fuentes</h2><div>{data.sources.map(item => <button key={item.id} onClick={() => setSource(item)}><FileText /><span><strong>[{item.id}] {item.name}</strong><small>{item.description}</small></span></button>)}</div><small>Referencias del PDF; no verificadas de nuevo.</small></section></div>
    <form className={s.composer} onSubmit={e => { e.preventDefault(); if (followUp.trim()) { setNotice('Prototipo: el análisis mostrado es un ejemplo fijo. Los seguimientos estarán disponibles al conectar el servicio de análisis.'); setFollowUp(''); } }}><label className="srOnly" htmlFor="follow-up">Pregunta de seguimiento</label><input id="follow-up" value={followUp} onChange={e => setFollowUp(e.target.value)} placeholder="Escribe una pregunta o pega un enlace…" /><button className="primary" disabled={!followUp.trim()} aria-label="Enviar seguimiento"><Send /></button></form>{notice && <p className={s.notice} role="status">{notice}</p>}
    {source && <Dialog title={`[${source.id}] ${source.name}`} onClose={() => setSource(null)}><p>{source.description}</p><p>Referencia del PDF utilizada en el diseño. No se ha verificado de nuevo y este prototipo no incluye un enlace al documento original.</p></Dialog>}
  </div>;
}
