package com.crosscheck.infrastructure.development;

public enum DevelopmentScenario {
    INSUFFICIENT_EVIDENCE, CLASSIFIED, ZERO_UNITS,
    SUPPORTED_BY_PUBLICATIONS, QUESTIONED_BY_PUBLICATIONS, TIED_PUBLICATIONS,
    TIMEOUT, UNAVAILABLE, INVALID_OUTPUT, CONFLICT, SESSION_UNAVAILABLE
}
